# Generated by Django 3.2.3 on 2021-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contrat_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.BooleanField(null=True),
        ),
    ]
