# Generated by Django 3.2.3 on 2021-06-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_update']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-date_update']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_update']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id']},
        ),
    ]
