# Generated by Django 3.2.3 on 2021-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210608_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payement_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
